[package]
name = "pct-id"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pct-id"
path = "src/main.rs"

[dependencies]
bench = { workspace = true }
bioio = { workspace = true }
pail = { workspace = true }
tools = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
glob = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
