[workspace]
resolver = "2"

members = [
    "crates/bioio",
    "crates/tools",
    "benchmarks/cloud-search",
    "benchmarks/hit-loss",
    "benchmarks/long-seqs",
    "benchmarks/mgnify",
    "benchmarks/mgy",
    "benchmarks/pct-id",
    "benchmarks/search-size",
]

[workspace.dependencies]
bioio = { path = "crates/bioio" }
tools = { path = "crates/tools" }

anyhow = "1.0.99"
clap = { version = "4.5.53", features = ["derive"] }
feisty = "0.1.0"
glob = "0.3.3"
indexmap = { version = "2.13.0", features = ["serde"] }
pail = "0.1.0"
rand = "0.9.2"
rayon = "1.11.0"
regex = "1.12.2"
serde = { version = "1.0.229", features = ["derive"] }
thread_local = "1.1.9"
toml = "1.1.4"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
