[package]
name = "thread-scaling"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "thread-scaling"
path = "src/main.rs"

[dependencies]
libsail = { workspace = true }
michi = { workspace = true }
serde = { workspace = true }
tabl = { workspace = true }
util = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
