[package]
name = "build-set"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "build-set"
path = "src/main.rs"

[dependencies]
libsail = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
michi = { workspace = true }
util = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
indexmap = { workspace = true }
serde = { workspace = true }
