[package]
name = "mgy"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "mgy"
path = "src/main.rs"

[dependencies]
bench = { workspace = true }
bioio = { workspace = true }
feisty = { workspace = true }
pail = { workspace = true }
tools = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
