[package]
name = "run"
version = "0.1.0"
edition = "2024"

[dependencies]
bioio = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
glob = { workspace = true }
indexmap = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
