[package]
name = "cutoffs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "cutoffs"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
libsail = { workspace = true }
michi = { workspace = true }
rayon = { workspace = true }
search = { workspace = true }
serde = { workspace = true }
util = { workspace = true }
