[package]
name = "search-size"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "search-size"
path = "src/main.rs"

[dependencies]
bioio = { workspace = true }
feisty = { workspace = true }
pail = { workspace = true }
tools = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
