[package]
name = "calibrate"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "calibrate"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
michi = { workspace = true }
scores = { workspace = true }
search = { workspace = true }
tabl = { workspace = true }
serde = { workspace = true }
util = { workspace = true }
