[package]
name = "scores"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "synth_results"
path = "src/bin/synth_results.rs"

[dependencies]
libsail = { workspace = true }
tabl = { workspace = true }
util = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
memchr = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
