[package]
name = "pid"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pid"
path = "src/main.rs"

[dependencies]
bench = { workspace = true }
libsail = { workspace = true }
pail = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }
glob = { workspace = true }
indexmap = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
